# Generated by Django 2.2.10 on 2020-02-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recreation', '0001_initial'),
        ('points', '0002_auto_20200213_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='attractions',
            field=models.ManyToManyField(to='recreation.Recreation'),
        ),
    ]
