# Generated by Django 2.2.10 on 2020-02-19 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adress', '0001_initial'),
        ('comments_reviews', '0001_initial'),
        ('points', '0003_points_attractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='adress',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adress.Adress'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='points',
            name='comments',
            field=models.ManyToManyField(to='comments_reviews.Reviews'),
        ),
    ]
